name: ai-marketplace-api
services:
- name: api
  github:
    repo: Limitenss/Ai_Marketplace
    branch: main
    deploy_on_push: true
  build_command: cd server && npm install
  run_command: cd server && npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: GROQ_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "8080"
  http_port: 8080
